Scotchy DotNet UI/Controllers/PriceController.cs
using API.Helper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Price.Model;
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;

namespace Price.Controllers
{
    public class PriceController : Controller
    {
        ScotchesAPI _scotchesAPI = new API.Helper.ScotchesAPI();

        public async Task<IActionResult> Index()
        {
            List<PriceDTO> dto = new List<PriceDTO>();
            HttpClient client = _scotchesAPI.InitializeClient();
            HttpResponseMessage res = await client.GetAsync("/api/prices");
            //Checking the response is successful or not which is sent using HttpClient    
            if (res.IsSuccessStatusCode)
            {
                //Storing the response details recieved from web api     
                var result = res.Content.ReadAsStringAsync().Result;
                //Deserializing the response recieved from web api and storing into the Employee list    
                dto = JsonConvert.DeserializeObject<List<PriceDTO>>(result);
            }
            //returning the employee list to view    
            return View(dto);
        }

        // GET: prices/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PriceDTO dto = new PriceDTO();
            HttpClient client = _scotchesAPI.InitializeClient();
            HttpResponseMessage res = await client.GetAsync("/api/prices/" + id);

            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                dto = JsonConvert.DeserializeObject<PriceDTO>(result);
            }

            if (dto == null)
            {
                return NotFound();
            }

            return View(dto);
        }

        // GET: prices/Create  
        public IActionResult Create()
        {
            return View();
        }

        // POST: prices/Create  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("distillerName,flavor,age,style,region,inStock,bottlingNotes,comment")] PriceDTO Price)
        {
            if (ModelState.IsValid)
            {
                HttpClient client = _scotchesAPI.InitializeClient();

                var content = new StringContent(JsonConvert.SerializeObject(Price, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }), Encoding.UTF8, "application/json");
                HttpResponseMessage res = client.PostAsync("/api/prices", content).Result;
                if (res.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(Price);
        }

        // GET: prices/Edit/1  
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PriceDTO dto = new PriceDTO();
            HttpClient client = _scotchesAPI.InitializeClient();
            HttpResponseMessage res = await client.GetAsync("/api/prices/" + id);

            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                dto = JsonConvert.DeserializeObject<PriceDTO>(result);
                ViewBag.returnUrl = Request.Headers["Referer"].ToString();
            }

            //var WishList = dto.SingleOrDefault(m => m.wishListName == wishListName);
            if (dto == null)
            {
                return NotFound();
            }

            return View(dto);

        }

        // POST: prices/Edit/1  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string id, string returnUrl, [Bind("distillerName,flavor,age,style,region,inStock,bottlingNotes,comment,_id")] PriceDTO Price)
        {
            if (id != Price._id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                HttpClient client = _scotchesAPI.InitializeClient();

                var content = new StringContent(JsonConvert.SerializeObject(Price), Encoding.UTF8, "application/json");
                HttpResponseMessage res = client.PutAsync("/api/prices/" + id, content).Result;
                if (res.IsSuccessStatusCode)
                {
                    //return RedirectToAction("Index");
                    return Redirect(returnUrl);
                }
            }
            ViewBag.returnUrl = returnUrl;
            return View(Price);
        }

        // GET: prices/Delete/1  
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            PriceDTO dto = new PriceDTO();
            HttpClient client = _scotchesAPI.InitializeClient();
            HttpResponseMessage res = await client.GetAsync("/api/prices/" + id);

            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                dto = JsonConvert.DeserializeObject<PriceDTO>(result);
            }

            //var WishList = dto.SingleOrDefault(m => m.wishListName == wishListName);
            if (dto == null)
            {
                return NotFound();
            }

            return View(dto);
        }

        // POST: prices/Delete/5  
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string id)
        {
            HttpClient client = _scotchesAPI.InitializeClient();
            HttpResponseMessage res = client.DeleteAsync("/api/prices/" + id).Result;
            if (res.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return NotFound();
        }
        public IActionResult Cancel(string returnUrl)
        {
            return Redirect(returnUrl);
        }

    }
}

Scotchy DotNet UI/Controllers/ScotchController.cs
using API.Helper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Scotch.Model;
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;

namespace Scotch.Controllers
{
    public class ScotchController : Controller
    {
        ScotchesAPI _scotchesAPI = new API.Helper.ScotchesAPI();

        public async Task<IActionResult> Index()
        {
            List<ScotchDTO> dto = new List<ScotchDTO>();
            HttpClient client = _scotchesAPI.InitializeClient();
            HttpResponseMessage res = await client.GetAsync("/api/scotches");
            //Checking the response is successful or not which is sent using HttpClient    
            if (res.IsSuccessStatusCode)
            {
                //Storing the response details recieved from web api     
                var result = res.Content.ReadAsStringAsync().Result;
                //Deserializing the response recieved from web api and storing into the Employee list    
                dto = JsonConvert.DeserializeObject<List<ScotchDTO>>(result);
            }
            //returning the employee list to view    
            return View(dto);
        }

        // GET: Scotches/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ScotchDTO dto = new ScotchDTO();
            HttpClient client = _scotchesAPI.InitializeClient();
            HttpResponseMessage res = await client.GetAsync("/api/scotches/" + id);

            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                dto = JsonConvert.DeserializeObject<ScotchDTO>(result);
                ViewBag.returnUrl = Request.Headers["Referer"].ToString();
            }

            if (dto == null)
            {
                return NotFound();
            }

            return View(dto);
        }

        // GET: Scotches/Create  
        public IActionResult Create()
        {
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();
            return View();
        }

        // POST: Scotches/Create  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("distillerName,flavor,age,style,region,inStock,bottlingNotes,comment")] ScotchDTO Scotch)
        {
            if (ModelState.IsValid)
            {
                HttpClient client = _scotchesAPI.InitializeClient();

                var content = new StringContent(JsonConvert.SerializeObject(Scotch, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }), Encoding.UTF8, "application/json");
                HttpResponseMessage res = client.PostAsync("/api/scotches", content).Result;
                if (res.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(Scotch);
        }

        // GET: Scotches/Edit/1  
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ScotchDTO dto = new ScotchDTO();
            HttpClient client = _scotchesAPI.InitializeClient();
            HttpResponseMessage res = await client.GetAsync("/api/scotches/" + id);

            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                dto = JsonConvert.DeserializeObject<ScotchDTO>(result);
                ViewBag.returnUrl = Request.Headers["Referer"].ToString();
            }

            //var WishList = dto.SingleOrDefault(m => m.wishListName == wishListName);
            if (dto == null)
            {
                return NotFound();
            }

            return View(dto);

        }

        // POST: Scotches/Edit/1  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string id, string returnUrl, [Bind("distillerName,flavor,age,style,region,inStock,bottlingNotes,comment,_id")] ScotchDTO Scotch)
        {
            if (id != Scotch._id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                HttpClient client = _scotchesAPI.InitializeClient();

                var content = new StringContent(JsonConvert.SerializeObject(Scotch), Encoding.UTF8, "application/json");
                HttpResponseMessage res = client.PutAsync("/api/scotches/" + id, content).Result;
                if (res.IsSuccessStatusCode)
                {
                    //return RedirectToAction("Index");
                    return Redirect(returnUrl);
                }
            }
            ViewBag.returnUrl = returnUrl;
            return View(Scotch);
        }

        // GET: Scotches/Delete/1  
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ScotchDTO dto = new ScotchDTO();
            HttpClient client = _scotchesAPI.InitializeClient();
            HttpResponseMessage res = await client.GetAsync("/api/scotches/" + id);

            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                dto = JsonConvert.DeserializeObject<ScotchDTO>(result);
                ViewBag.returnUrl = Request.Headers["Referer"].ToString();
            }

            //var WishList = dto.SingleOrDefault(m => m.wishListName == wishListName);
            if (dto == null)
            {
                return NotFound();
            }

            return View(dto);
        }

        // POST: Scotches/Delete/5  
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string id)
        {
            HttpClient client = _scotchesAPI.InitializeClient();
            HttpResponseMessage res = client.DeleteAsync("/api/scotches/" + id).Result;
            if (res.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return NotFound();
        }
        public IActionResult Cancel(string returnUrl)
        {
            return Redirect(returnUrl);
        }

    }
}

Scotchy DotNet UI/Views/Shared/_BackButton.cshtml
<div class="hidden">
    <input type="hidden" name="returnUrl" value="@ViewBag.returnUrl" />
</div>
<div>
    <a href="@ViewBag.returnUrl" class="btn btn-default">Back</a>
</div>

Scotchy DotNet UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/ScotchySkin.css"  />
        <link rel="stylesheet" href="~/css/tables.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Scotchy</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Scotch" asp-action="Index"><i class="fas fa-folder-open"></i> Cabinet</a></li>
                    <li><a asp-area="" asp-controller="Tasting" asp-action="Index"><i class="fas fa-glass-martini"></i> Tastings</a></li>
                    <li><a asp-area="" asp-controller="Wishlist" asp-action="Index"><i class="fas fa-file-alt"></i> Wish Lists</a></li>
                    <li><a asp-area="" asp-controller="Price" asp-action="Index"><i class="fas fa-dollar-sign"></i> Price List</a></li>
                    <li><a asp-area="" asp-controller="Settings" asp-action="Index"><i class="fas fa-cogs"></i> Settings</a></li>
                    <li><a asp-area="" asp-controller="SignOut" asp-action="Index"><i class="fas fa-sign-out-alt"></i> Sign Out</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <br />
        <footer>
            <p>&copy; 2018 - HobbsSquad</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Scotchy DotNet UI/Views/Shared/_TableHeader.cshtml
<thead>
    <tr>
        @if (ViewBag.TableProps.detailsButton)
        {
            <th class="openColumn"></th>
        }
        @foreach (var column in ViewBag.Columns)
        { 
            <th class="textColumn">
                <span>@column.header</span>
            </th>
        }
        @if (ViewBag.TableProps.editButton || ViewBag.TableProps.deleteButton)
        {
            <th class="openColumn"></th>
        }

    </tr>
</thead>

Scotchy DotNet UI/Views/Shared/_TableRow.cshtml
@foreach (var row in Model) {
    <tr>
        @foreach (var column in ViewBag.Columns)
        {
            <td class="textColumn">
                
                @Html.DisplayFor(modelItem => row.column.fieldName)
            </td>
        }
    </tr>
}